url: "https://mesaredux.mesagrey.ca" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "MESÎ»REDUX" # the name of your site, e.g. ACME Corp.
excerpt_separator: <!--ex-->
repository: Bored-Entertainment/mesaredux
collections:
  games:
    output: true
    permalink: /games/:path/

plugins:
  - _plugins/nested_collections.rb

exclude:
  - "tempgames"
