url: "https://mesaredux.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
domain: "mesaredux.com"
title: "MESλREDUX" # the name of your site, e.g. ACME Corp.
excerpt_separator: <!--ex-->
repository: Bored-Entertainment/mesaredux

collections:
  games:
    output: true
    permalink: /games/:path/

compress_images:
  images_path:
    - "_games/**/thumb.png"
    - "_games/**/**/thumb.png"
    - "_games/**/**/**/thumb.png"
imageoptim:
  gifsicle: true
  jpegoptim:
    strip: "all"
  jpegtran: true
  oxipng: false
  allow_lossy: false
svgo: false


plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-compress-images

exclude:
  - "vendor"
  - ".bundle"
  - "Gemfile"
  - "Gemfile.lock"
  - ".github"
  - "README.md"
  - "LICENSE"

jekyll-minifier:
  exclude:
    - "games/**/index/src/**"
  compress_css: true
  compress_javascript: true
  compress_json: true    
  compress_html: true
  preserve_line_breaks: false
  remove_comments: true
