url: "https://mesaredux.mesagrey.ca" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "MESÎ»REDUX" # the name of your site, e.g. ACME Corp.
excerpt_separator: <!--ex-->
repository: Bored-Entertainment/mesaredux

collections:
  games:
    output: true
    permalink: /games/:path/

compress_images:
  images_path:
    - "_games/**/thumb.png"
    - "_games/**/**/thumb.png"
imageoptim:
  gifsicle: true
  jpegoptim:
    strip: "all"
  jpegtran: true
  svgo: true
  oxipng: false
  allow_lossy: false


plugins:
  - _plugins/nested_collections.rb
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-compress-images

exclude:
  - "tempgames"
  - "vendor"
  - ".bundle"
  - "Gemfile"
  - "Gemfile.lock"
