# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Deploy Jekyll site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Half-Life ZIP
        run: |
          mkdir -p _games/hl/index/src/hl
          curl -L -H "Accept: application/octet-stream" -A "Mozilla/5.0" \
            -o "_games/hl/index/src/hl/half-life.zip" \
            "https://github.com/greymesa/files/releases/download/half-life/half-life.zip"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-version: 0

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
           
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy-to-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Notify Discord of deployment status
        if: always()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "MESλREDUX Deployment"
          color: ${{ job.status == 'success' && '0xFF4500' || '0xFF0000' }}
          description: ${{ job.status == 'success' && 'MESλREDUX has been built and deployed successfully! See changes at https://mesaredux.mesagrey.ca' || 'The deployment failed! Check the workflow logs for details.' }}
